name: Releases

on: 
  push:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: reecetech/version-increment@2023.3.1
      id: version
      with:
        scheme: semver
        increment: patch
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "v{{ steps.version.outputs.version }}.tar.gz,v{{ steps.version.outputs.version }}.zip"
        
